### ISSUE TITLE
ctrl+v paste does not copy text correctly in linux(wsl)

### ISSUE THREAD

**Issue by Eboubaker** [magmax/python-readchar#95]
Take this sample
```python
import sys

import readchar

while True:
    sys.stdout.write(readchar.readchar())
    sys.stdout.flush()
```
if I copy the text `ClientMessage.to_server` and paste it into the program terminal in linux(wsl) I would get unordered characters 
 or missing characters like this `ClientMto_seerrv`
 
on windows cmd it works fine

**Comment by Cube707** [comment]
On first read this sounds related to https://github.com/magmax/python-readchar/issues/73#issuecomment-1190115146. Readchar can only guarantee character recognition inside its own function and behaviour outside of them is not defined.

So for your example, the first character will be read and returned by readchar, but its not clear whar will happen to the rest of the input during the printing and flushing code... 

Readchar is currently not really ready to handle input streams, only human input which is guaranteed to be slow enough.

I am working on this on the context-mamager branch, which would allow for exacly this kind of behaviour, but this faces its own issue currently.

**Comment by Eboubaker** [comment]
Understandable, can you put this feature in your list of functionality of your progress. And close this afterwards

**Comment by magmax** [comment]
Anyways... Have you tried to use the terminal functionality, by pressing `CTRL+SHIFT+V`?

**Comment by Cube707** [comment]
this should be solved as soon as the feature is merged, but I currently cant get it to work consistently in all cases 😢 

you can however install the developent version in your enviroment and test if it solves your usecase. simply run:

```bash
pip install git+https://github.com/magmax/python-readchar@contexmanager
```

**Comment by Eboubaker** [comment]
> this should be solved as soon as the feature is merged, but I currently cant get it to work consistently in all cases 😢
> 
> you can however install the developent version in your enviroment and test if it allready solves your usecase. simply run:
> 
> ```shell
> pip install git+https://github.com/magmax/python-readchar@contexmanager
> ```


I tried using the .4-dev version it did not fix the problem, however I tried [this](https://github.com/magmax/python-readchar/issues/73#issuecomment-1053547318)  snippet  from the other issue you mentioned and it worked (I removed the time delay) maybe you should include this buffering technique in your implementation using some option or function call to activate buffered (per request)

**Comment by Eboubaker** [comment]
I removed the old install and installed from the contextmanager and no change happened bug still exists,
however I tried a code snippet from the issue you mentioned (I removed delay) and the input did not have problems ( i copied big text file)
```python
import os
import time
import fcntl
import termios

class NonBlockingInput(object):

    def __enter__(self):
        # canonical mode, no echo
        self.old = termios.tcgetattr(sys.stdin)
        new = termios.tcgetattr(sys.stdin)
        new[3] = new[3] & ~(termios.ICANON | termios.ECHO)
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, new)

        # set for non-blocking io
        # orig_fl = fcntl.fcntl(sys.stdin, fcntl.F_GETFL)
        # fcntl.fcntl(sys.stdin, fcntl.F_SETFL, orig_fl | os.O_NONBLOCK)

    def __exit__(self, *args):
        # restore terminal to previous state
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, self.old)

with NonBlockingInput():
    while True:
        sys.stdout.write(sys.stdin.read(1))
        sys.stdout.flush()

```

it would be nice to have this non-blocking input added as an activated functionality with a function call for example to activate it and another to deactivate. or just simply by using with keyword

**Comment by Eboubaker** [comment]
looking into the pr it seems you added a class "Readchar" that has that code but can't use it in import because it is not exported in __init__ module

**Comment by Cube707** [comment]
> but can't use it in import because it is not exported in __init__ module __all__

Yea its not jet externalised and you have to import it directly from the submodules, `from readchar._read_posix import Readchar` would have worked. Its still under development 😅

But good to know that it allready fixes your issue
